import { Check, ExternalLink, RefreshCw } from 'lucide-react';
import type { MapSources } from './lib/mapSources';
import type { useFieldLayers } from './useFieldLayers';
export default function FieldLayerControls({ sources, onChange, state, onHigueruela, detailBusy }: { sources: MapSources; onChange: (sources: MapSources) => void; state: ReturnType<typeof useFieldLayers>; onHigueruela: () => void; detailBusy: boolean }) {
  return <div className="field-layers-controls">
    <button className="layer-toggle" aria-pressed={sources.ielig} onClick={() => onChange({ ...sources, ielig: !sources.ielig })}><span className={'checkbox ' + (sources.ielig ? 'checked' : '')}>{sources.ielig && <Check size={14} />}</span><span><b>Lugares geológicos · IELIG</b><small>Delimitaciones, fichas e informes · IGME-CSIC</small></span></button>
    {sources.ielig && <div className="source-layer-settings"><p className="source-query-status" role="status">{state.busy ? 'Consultando IELIG…' : state.zoomHint ? 'Acerca el mapa para consultar lugares.' : state.error || `${state.sites.length} lugares públicos en esta zona.`}</p>{state.error && <button className="text-button" onClick={state.reload}><RefreshCw size={13} />Reintentar IELIG</button>}{state.truncated && <p className="meta">Consulta limitada. Acerca el mapa para ver todos los lugares.</p>}{!!state.sites.length && <details className="bdmin-locations"><summary>Ver lugares geológicos</summary><div>{state.sites.slice(0, 30).map(site => <button key={site.code} onClick={() => state.open(site)}><span><b>{site.code} · {site.name}</b><small>{site.interest || 'Ficha y documentación'}</small></span></button>)}</div>{state.sites.length > 30 && <p className="meta">Primeras 30 fichas. Acerca el mapa para reducir la zona.</p>}</details>}<p className="meta">Rombos y límites morados: patrimonio geológico. Tócalos para abrir sus fichas y documentación. Un LIG no es una autorización de recogida.</p></div>}
    <button className="text-button" disabled={detailBusy} onClick={onHigueruela}>{detailBusy ? 'Abriendo ficha…' : 'Cañada–Villar · Casas de la Higueruela'}</button>
    <button className="layer-toggle" aria-pressed={sources.protected} onClick={() => onChange({ ...sources, protected: !sources.protected })}><span className={'checkbox ' + (sources.protected ? 'checked' : '')}>{sources.protected && <Check size={14} />}</span><span><b>Espacios protegidos · CLM</b><small>ENP, Natura 2000 y zonas periféricas · JCCM</small></span></button>
    {sources.protected && <div className="source-layer-settings"><div className="field-legend"><span><i className="enp" />Espacios naturales protegidos</span><span><i className="natura" />Red Natura 2000</span><span><i className="zpp" />Zonas periféricas de protección</span></div><label className="opacity-label">Opacidad de espacios protegidos<input aria-label="Opacidad de espacios protegidos" type="range" min=".15" max="1" step=".05" value={sources.protectedOpacity} onChange={event => onChange({ ...sources, protectedOpacity: Number(event.target.value) })} /></label><p className="meta">Cobertura: Castilla-La Mancha. Toca el mapa para consultar nombres, figuras y documentos disponibles. No incluye todas las posibles restricciones.</p><a className="text-button" href="https://geoservicios.castillalamancha.es/" target="_blank" rel="noopener noreferrer"><ExternalLink size={13} />Cartografía oficial JCCM</a>{state.protectionError && <p className="field-query-error" role="status">Parte de la cartografía no cargó. Desactiva y vuelve a activar esta capa para reintentar.</p>}</div>}
  </div>;
}
