export type FeaturedSite = { code: string; name: string; area: string; material: string; note: string; category: 'volcanic' | 'color' | 'sedimentary'; priority?: string };
export const FEATURED_SITES: FeaturedSite[] = [
  { code: 'TM142', name: 'Casas de la Higueruela', area: 'Cañada de Calatrava · Villar del Pozo', material: 'Costras de hierro y manganeso; facies con pisolitos en matriz de ilita y caolinita.', note: 'Tres afloramientos documentados. La ficha menciona un refugio de fauna y recogida para investigación.', category: 'color', priority: 'Fe–Mn' },
  { code: 'TMs104', name: 'El Chorrillo', area: 'Pozuelo de Calatrava', material: 'Brechas cementadas por mineralizaciones de hierro y manganeso de origen hidrotermal.', note: 'Complemento de Higueruela para observar mineralizaciones. La ficha no proporciona una receta ni un análisis de una muestra.', category: 'color', priority: 'Fe–Mn' },
  { code: 'TM138', name: 'Volcanismo de Poblete', area: 'Poblete · Ciudad Real', material: 'Melilititas olivínicas, tobas y piroclastos hidromagmáticos, paleosuelos y carbonatos.', note: 'Incluye informes, columna geológica y ortofotos. La ficha señala tráfico peligroso en taludes y permisos para la cantera.', category: 'volcanic' },
  { code: 'TM150', name: 'Volcán y maar del Acebuche', area: 'Campo de Calatrava', material: 'Nefelinitas olivínicas y oleadas piroclásticas de un maar asociado.', note: 'Permite comparar rocas volcánicas y depósitos hidromagmáticos. Revisa accesos y condiciones en la ficha.', category: 'volcanic' },
  { code: 'TM147', name: 'Cuevas Negras y La Cornudilla', area: 'Granátula · Valenzuela de Calatrava', material: 'Basanita, piroclastos y costra carbonatada sobre la colada de Los Negrizales.', note: 'Interesante para comparar litologías volcánicas. La ficha indica recogida de minerales para investigación.', category: 'volcanic', priority: 'Comparar rocas' },
  { code: 'TM157', name: 'Volcanes de La Atalaya', area: 'Calzada de Calatrava', material: 'Nefelinitas olivínicas en La Atalaya; basaltos y basanitas en Las Yeguas y Salvatierra.', note: 'Varias litologías cercanas entre sí. No confundir este conjunto con el parque de La Atalaya de Ciudad Real.', category: 'volcanic', priority: 'Comparar rocas' },
  { code: 'TM146', name: 'Cerro Gordo y Barondillo', area: 'Granátula · Valenzuela de Calatrava', material: 'Lavas, escorias, lapilli y depósitos hidromagmáticos con xenolitos de peridotita ricos en olivino.', note: 'Secciones musealizadas para observar. La Sima emite CO₂: sigue el itinerario habilitado. La ficha limita la recogida a investigación.', category: 'volcanic', priority: 'Observar materiales' },
  { code: 'TM144', name: 'Maar de La Nava', area: 'Almagro · Pozuelo · Valenzuela', material: 'Oleadas piroclásticas, fragmentos del sustrato y xenolitos peridotíticos.', note: 'Propiedad privada ganadera; la ficha considera el uso turístico no apropiado. No planifiques un acceso sin autorización.', category: 'volcanic' },
  { code: 'TMs114', name: 'Relleno de un paleocanal', area: 'Villanueva de San Carlos', material: 'Depósitos cuaternarios sobre arcillas terciarias.', note: 'Una pista para investigar tierras sedimentarias; no demuestra plasticidad ni aptitud cerámica.', category: 'sedimentary' },
  { code: 'PT041', name: 'Tobas del Campo de Montiel', area: 'Campo de Montiel', material: 'Travertinos y tobas calcáreas sobre materiales triásicos; documentación con lutitas rojas y niveles yesíferos.', note: 'Toba calcárea, no ceniza volcánica. La ficha documenta depósitos ausentes en los mapas 1:50.000 que consultó.', category: 'sedimentary' },
  { code: 'CI240', name: 'Fosfatos de Fontanarejo', area: 'Fontanarejo', material: 'Conglomerados fosfáticos y pizarras alteradas con nódulos de fosfato, asociados a fósiles excepcionales.', note: 'Principalmente para observar. La ficha indica malas condiciones de afloramiento y recogida para investigación.', category: 'sedimentary' },
];
export const featuredSite = (code: string) => FEATURED_SITES.find(site => site.code.toLowerCase() === code.toLowerCase());
